FORMAT: 1A
HOST: https://api.scaleway.com/

# Scaleway API

The Scaleway API allows you to manage servers and resources in a simple, programmatic way using conventional HTTP requests. 
All features you will find in the web control panel are also available through the API.

## Request and response

Our api works over https and is accessed from two endpoint:

- `account.scaleway.com` domain related to account actions
- `api.scaleway.com` domain related to compute actions

All data is sent and received as json.

## Constructing Requests

Requests are made of two components:

- Base URL: `https://api.scaleway.com`
- Resource path: `servers`

To construct a proper request, you need to format the URL as follows:

`https://api.scaleway.com/{resource}`

Example: `https://api.scaleway.com/volumes/f929fe39-63f8-4be8-a80e-1e9c8ae22a76`

The following code is an example request to retrieve detailed informations about a volume

```
% curl -H 'X-Auth-Token: 017ce0ce-20ec-4d4ez-b44c-e561a23481d2c' -H 'Content-Type: application/json' https://api.scaleway.com/volumes/f929fe39-63f8-4be8-a80e-1e9c8ae22a76 -i

HTTP/1.1 200 OK
Server: nginx
Date: Thu, 22 May 2014 07:55:00 GMT
Content-Type: application/json
Content-Length: 1345
Connection: keep-alive
X-Sentry-ID: None
Strict-Transport-Security: max-age=86400

{
  "volumes": [
    {
      "export_uri": null,
      "id": "f929fe39-63f8-4be8-a80e-1e9c8ae22a76",
      "name": "volume-0-1",
      "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
      "server": null,
      "size": 10000000000,
      "volume_type": "l_ssd"
    },
    {
      "export_uri": null,
      "id": "0facb6b5-b117-441a-81c1-f28b1d723779",
      "name": "volume-0-2",
      "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
      "server": null,
      "size": 20000000000,
      "volume_type": "l_ssd"
    }
  ]
}
```

## Basic Authentication

You authenticate to the API by requesting a token. You can create a token from the `account.scaleway.com` domain related to account actions with a POST request on the /tokens HTTP resource.

Basic Authentication process:

- Query via POST request the /tokens resource [see here how to](https://developer.scaleway.com/#tokens-tokens-post)

- Supply an "X-Auth-Token" header followed by the token you get previously, e.g. "4e0b46e4-7c1d-44d4-8ba6-dc5f80694397"

```
curl -X GET -H "X-Auth-Token: 4e0b46e4-7c1d-44d4-8ba6-dc5f80694397" -H "Content-Type: application/json" https://account.scaleway.com/{resources}
```

## Errors

We use conventional HTTP response codes to indicate success or failure of an API request.

In general, codes in the 2xx range indicate success, codes in the 4xx range indicate an error that resulted from the provided information (e.g., a required parameter is missing), and codes in the 5xx range indicate an error with our servers.

### HTTP Status Code Summary

- `200 OK` - Everything worked as expected.
- `400 Bad Request` - Often missing a required parameter.
- `401 Unauthorized` - No valid API key provided.
- `402 Request Failed` - Parameters were valid but request failed.
- `403 Forbidden` - Insufficient privileges to access requested resource.
- `404 Not Found` - The requested item doesn't exist.
- `50x` Server errors - something went wrong on api domain's end.

Input and output data must be valid JSON with appropriate Content-Type header set.

### Attributes

- type:
 
  - `invalid_request_error`: Occur when your request has invalid parameters.
  - `invitalid_auth`: Arise when there is a problem of authentication.
  - `uknown_resource`: Occur when the resource doesn't exist.
  - `authorization_required`: You don't have sufficient right to access the resource.
  - `api_error`: API errors use in case of problem with api domain's servers

- message:
 
  - A human readable error giving more details about the error

- fields (Optional):

  - An array of parameters with an human readable message giving more details about the error.

### Errors responses example 

+ Response 400 (application/json)

        {
            "fields": {
                "email": [
                    "incorrect email address",
                    "required key not provided"
                ],
                "firstname": [
                    "length of value must be at least 2",
                    "required key not provided"
                ],
                "lastname": [
                    "length of value must be at least 2",
                    "required key not provided"
                ]
            },
            "message": "Validation Error",
            "type": "invalid_request_error"
        }

+ Response 401 (application/json)

        {
            "message": "The header 'X-Auth-Token' is missing",
            "type": "invalid_auth"
        }

+ Response 403 (application/json)

        {
          "message": "The token provided doesn't have the requested permission.",
          "type": "authorization_required"
        }

+ Response 404 (application/json)

        {
            "message": "User not found",
            "type": "unknown_resource"
        }
        
        
### group Tokens

A Token is an identifier associated with your account. We use this token to authenticate commands in our APIs.
 
#### Tokens [/tokens]

##### Create a token [POST]

Authenticates a user against their username, password, and then returns a new Token, which can be used until it expires.

The response is an object that has a key called `token`. This key contain a standard `token` object.

+ Attributes
    + email: `jsnow@got.com` (string, required) - User email
    + password: `winteriscoming` (string, required) - User password
    + expires: `false` (boolean, optional) - Set if you want a Token wich doesn't expire (default: true)

+ Request (application/json)

    + Body

            {
                "email": "jsnow@got.com",
                "password": "winteriscoming",
                "expires": false
            }

+ Response 201 (application/json)

    + Headers
           
            location: https://account.cloud.online.net/tokens/9de8f869-c58e-4aa3-9208-2d4eaff5fa20

    + Body

            {
                "token": {
                    "creation_date": "2014-05-22T08:05:57.556385+00:00",
                    "expires": null,
                    "id": "9de8f869-c58e-4aa3-9208-2d4eaff5fa20",
                    "inherits_user_perms": true,
                    "permissions": [],
                    "roles": {
                      "organization": null,
                      "role": null
                    },
                    "user_id": "5bea0358-db40-429e-bd82-914686a7e7b9"
                }
            }

##### List all tokens [GET]

List all Tokens associate with your account

The response is an object that has a key called `tokens`. This key contain an array of token objects each of which contain the standard `token` attributes.

+ Response 200 (application/json)

        {
            {
                "tokens": [
                    {
                        "creation_date": "2014-03-13T10:53:11.456319+00:00",
                        "expires": null,
                        "id": "4e5570fb-c854-5349-979f-9f51d608d34z",
                        "inherits_user_perms": true,
                        "permissions": [],
                        "roles": {
                            "organization": null,
                            "role": null
                        },
                        "user_id": "5bea0358-db40-429e-bd82-953016a7e2s7"
                    },
                   {
                        "creation_date": "2014-05-19T18:05:47.304433+00:00",
                        "expires": "2014-05-20T14:05:06.393875+00:00",
                        "id": "654c95b0-2cf5-41a3-b3cc-733ffba4b4b7",
                        "inherits_user_perms": true,
                        "permissions": [],
                        "roles": {
                            "organization": null,
                            "role": null
                        },
                        "user_id": "5bea0358-db40-429e-bd82-953016a7e2s7"
                    }
                ]
            }
        }


#### Token [/tokens/{token_id}]

+ Parameters
    + token_id (required, string, `654c95b0-2cf5-41a3-b3cc-733ffba4b4b7`)... Token unique identifier

##### Retrieve a token [GET]

List an individual Token

The response is an object that has a key called `token`. This key contain a standard `token` object.

+ Response 200 (application/json)

        {
            "token": {
                "creation_date": "2014-05-22T08:06:51.742826+00:00",
                "expires": "2014-05-20T14:05:06.393875+00:00",
                "id": "654c95b0-2cf5-41a3-b3cc-733ffba4b4b7",
                "inherits_user_perms": true,
                "permissions": [],
                "roles": {
                    "organization": null,
                    "role": null
                },
                "user_id": "5bea0358-db40-429e-bd82-953016a7e2s7"
            }
        }


##### Update a token [PATCH]

Increase Token expiration time of 30 minutes

The response is an object that has a key called `token`. This key contain a standard `token` object.

+ Response 200 (application/json)

        {
            "token": {
                creation_date": "2014-05-22T08:06:51.742826+00:00",
                "expires": "2014-05-22T11:18:07.786841+00:00",
                "id": "654c95b0-2cf5-41a3-b3cc-733ffba4b4b7",
                "inherits_user_perms": true,
                "permissions": [],
                "roles": {
                    "organization": null,
                    "role": null
                },
                "user_id": "5bea0358-db40-429e-bd82-953016a7e2s7"
            }
        }



##### Remove a token [DELETE]

Delete an individual token

The response code is a 204, which means that the action was successful with no returned body data.

+ Response 204

### group Organizations

This resources of API methods allows you to get your Organizations informations

#### Organizations [/organizations]

##### List all organizations [GET]

List all Organizations associate with your account

The response is an object that has a key called `organizations`. This key contain an array of organization objects each of which contain the standard `organization` attributes.

+ Response 200 (application/json)

        {
          "organizations": [
            {
              "id": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "name": "jsnow@got.com",
              "users": [
                {
                  "email": "jsnow@got.com",
                  "firstname": "John",
                  "fullname": "John Snow",
                  "id": "59a98700-8622-4495-a11a-e1efbfac5972",
                  "lastname": "Snow",
                  "organizations": [
                    {
                      "id": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                      "name": "jsnow@got.com"
                    }
                  ],
                  "roles": [
                    {
                      "organization": {
                        "id": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                        "name": "jsnow@got.com"
                      },
                      "role": "manager"
                    }
                  ],
                  "ssh_public_keys": []
                }
              ]
            }
          ]
        }


### group Users

#### User [/users/{user_id}]

+ Parameter
    + user_id (required, string, `5bea0358-db40-429e-bd82-953016a7e2s7`)... User unique identifier

##### Retrieve a user [GET]

List informations about your user account

The response is an object that has a key called `user`. This key contain a standard `user` object.

+ Response 200 (application/json)


            "user": {
                "email": "jsnow@got.com",
                "firstname": "John",
                "fullname": "John Snow",
                "id": "5bea0358-db40-429e-bd82-953016a7e2s7",
                "lastname": "Snow",
                "organizations": null,
                "roles": null,
                "ssh_public_keys": null
            }
            
### group Servers

A Server is a dedicated machine for your own use. `servers` endpoint allow you to create, list or delete your servers.

#### Servers [/servers]

##### Create a new server [POST]

Create a new server

The response is an object that has a key called `server`. This key contain a standard `server` object.

+ Attributes
    
    + name: `my_server` (string, required) - The server name
    + organization: `000a115d-2852-4b0a-9ce8-47f1134ba95a` (string, required) - Organization unique identifier
    + image: `85917034-46b0-4cc5-8b48-f0a2245e357e` (string, required) - Image unique identifier
    + volumes: `volumes: {1: {name: "vol_demo", organization: "ecc1c86a-eabb-43a7-9c0a-77e371753c0a", size: 10000000000, volume_type: "l_sdd"` (array, required) - A list of volumes identifier to be attached to the server
    + tags: `[test, www]` (array, optional) - A list of tags

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "name": "my_server",
              "image": "85917034-46b0-4cc5-8b48-f0a2245e357e",
              "tags": ["test", "www"]
            }

+ Response 201 (application/json)

    + Headers
    
            location: https://api.cloud.online.net/servers/3cb18e2d-f4f7-48f7-b452-59b88ae8fc8c

    + Body

            {
              "server": {
                "bootscript": null,
                "dynamic_public_ip": false,
                "id": "3cb18e2d-f4f7-48f7-b452-59b88ae8fc8c",
                "image": {
                  "id": "85917034-46b0-4cc5-8b48-f0a2245e357e",
                  "name": "ubuntu working"
                },
                "name": "my_server",
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                "private_ip": null,
                "public_ip": null,
                "state": "running",
                "tags": [
                  "test",
                  "www"
                ],
                "volumes": {
                  "0": {
                    "export_uri": null,
                    "id": "d9257116-6919-49b4-a420-dcfdff51fcb1",
                    "name": "vol simple snapshot",
                    "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                    "server": {
                      "id": "3cb18e2d-f4f7-48f7-b452-59b88ae8fc8c",
                      "name": "my_server"
                    },
                    "size": 10000000000,
                    "volume_type": "l_ssd"
                  }
                }
              }
            }

##### List all servers [GET]

List all servers associate with your account

The response is an object that has a key called `servers`. This key contain an array of server objects each of which contain the standard `server` attributes.

+ Response 200 (application/json)

        {
          "servers": [
            {
              "bootscript": null,
              "dynamic_public_ip": false,
              "id": "741db378-6b87-46d4-a8c5-4e46a09ab1f8",
              "image": {
                "id": "85917034-46b0-4cc5-8b48-f0a2245e357e",
                "name": "ubuntu working"
              },
              "name": "my_server",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "private_ip": null,
              "public_ip": null,
              "state": "running",
              "tags": [
                "test",
                "www"
              ],
              "volumes": {
                "0": {
                  "export_uri": null,
                  "id": "c1eb8f3a-4f0b-4b95-a71c-93223e457f5a",
                  "name": "vol simple snapshot",
                  "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                  "server": {
                    "id": "741db378-6b87-46d4-a8c5-4e46a09ab1f8",
                    "name": "my_server"
                  },
                  "size": 10000000000,
                  "volume_type": "l_ssd"
                }
              }
            },
            {
              "bootscript": null,
              "dynamic_public_ip": false,
              "id": "0e9f85af-b6aa-401e-a00d-484f832c5024",
              "image": {
                "id": "85917034-46b0-4cc5-8b48-f0a2245e357e",
                "name": "ubuntu working"
              },
              "name": "my_server",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "private_ip": null,
              "public_ip": null,
              "state": "running",
              "tags": [
                "test",
                "www"
              ],
              "volumes": {
                "0": {
                  "export_uri": null,
                 "id": "fb09bb31-ecd9-4dff-8b55-b6e45715199d",
                  "name": "vol simple snapshot",
                  "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                  "server": {
                    "id": "0e9f85af-b6aa-401e-a00d-484f832c5024",
                    "name": "my_server"
                  },
                  "size": 10000000000,
                  "volume_type": "l_ssd"
                }
              }
            }
          ]
        }


#### Server [/servers/{server_id}]

+ Parameters

    + server_id (required, string, `741db378-6b87-46d4-a8c5-4e46a09ab1f8`)... Server unique identifier

##### Retrieve a server [GET]

List an individual server

The response is an object that has a key called `server`. This key contain a standard `server` object.

+ Response 200 (application/json)

        {
          "server": {
            "bootscript": null,
            "dynamic_public_ip": false,
            "id": "741db378-6b87-46d4-a8c5-4e46a09ab1f8",
            "image": {
              "id": "85917034-46b0-4cc5-8b48-f0a2245e357e",
              "name": "ubuntu working"
            },
            "name": "my_server",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "private_ip": null,
            "public_ip": null,
            "state": "running",
            "tags": [
              "test",
              "www"
            ],
            "volumes": {
              "0": {
                "export_uri": null,
                "id": "c1eb8f3a-4f0b-4b95-a71c-93223e457f5a",
                "name": "vol simple snapshot",
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                "server": {
                  "id": "741db378-6b87-46d4-a8c5-4e46a09ab1f8",
                  "name": "my_server"
                },
                "size": 10000000000,
                "volume_type": "l_ssd"
              }
            }
          }
        }

##### Update a server [PUT]

Update details about a server

The response is an object that has a key called `server`. This key contain a standard `server` object.

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
              "bootscript": null,
              "dynamic_public_ip": false, 
              "id": "741db378-6b87-46d4-a8c5-4e46a09ab1f8",
              "image": {
                    "id": "85917034-46b0-4cc5-8b48-f0a2245e357e", 
                    "name": "ubuntu working"
                  }, 
              "name": "my_server", 
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a", 
              "private_ip": null, 
              "public_ip": null, 
              "state": "running",
              "tags": [
                "test", 
                "www", 
                "new"
              ], 
              "volumes": {
                "0": {
                  "export_uri": null, 
                  "id": "c39b49f4-1804-4d03-96b4-952896b0918e", 
                  "name": "vol simple snapshot", 
                  "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a", 
                  "server": {
                    "id": "345b862b-9198-4633-94a5-3f0307702652", 
                    "name": "my_server"
                  }, 
                  "size": 10000000000, 
                  "volume_type": "l_ssd"
                }
              }
            }


+ Response 200 (application/json)

        {
          "server": {
            "bootscript": null,
            "dynamic_public_ip": false,
            "id": "741db378-6b87-46d4-a8c5-4e46a09ab1f8",
            "image": {
              "id": "85917034-46b0-4cc5-8b48-f0a2245e357e",
              "name": "ubuntu working"
            },
            "name": "my_server",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "private_ip": null,
            "public_ip": null,
            "state": "running",
            "tags": [
              "prod",
              "www",
               "new"
            ],
            "volumes": {
              "0": {
                "export_uri": null,
                "id": "c1eb8f3a-4f0b-4b95-a71c-93223e457f5a",
                "name": "vol simple snapshot",
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                "server": {
                  "id": "741db378-6b87-46d4-a8c5-4e46a09ab1f8",
                  "name": "my_server"
                },
                "size": 10000000000,
                "volume_type": "l_ssd"
              }
            }
          }
        }

##### Remove a server [DELETE]

Delete a server

The response code is a 204, which means that the action was successful with no returned body data.

+ Response 204


#### Actions [/servers/{server_id}/action]

A collection of actions to be applied on a server

+ Parameters

    + server_id (required, string, `741db378-6b87-46d4-a8c5-4e46a09ab1f8`)... Server unique identifier

##### List all actions [GET]

List all actions available for the secified server

The response is an object that has a key called `actions`. This key contain an array of action

+ Response 200 (application/json)
     
        {
          "actions": [
            "poweron",
            "poweroff",
            "reboot"
          ]
        }

##### Execute an action [POST]

Execute an action on a server

The response is an object that has a key called `task`. This key contain a standard `task` object.

+ Parameters 

    + server_id (required, string, `741db378-6b87-46d4-a8c5-4e46a09ab1f8`)... Server unique identifier
    + action (required, string, `poweron`)... Action to execute

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body
    
            {
              "action": "poweroff"
            }

+ Response 202 (application/json)

    + Header

            location: https://api.cloud.online.net/tasks/a8a1775c-0dda-4f52-87b2-4e8101d68d6e

    + Body
    
            {
              "task": {
                "description": "server_poweroff",
                "href_from": "/servers/741db378-6b87-46d4-a8c5-4e46a09ab1f8/action",
                "id": "a8a1775c-0dda-4f52-87b2-4e8101d68d6e",
                "progress": "0",
                "status": "pending"
              }
            }

### group Volumes

A Volume abstracts data storage operations for your servers in a flexible manner. `volumes` endpoint allow you to create, list or delete your volumes.

#### Volumes [/volumes]

##### Create a new volume [POST]

Create a new volume

The response is an object that has a key called `volume`. This key contain a standard `volume` object.

+ Attributes
    + name: `volume-0-3` (string, required) - The volume name
    + organization: `000a115d-2852-4b0a-9ce8-47f1134ba95a` (string, required) - Unique organization identifier
    + volume_type: `l_ssd` (string, required) - The volume type
    + size: `10000000000` (number, required) - The volume size

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body
    
            {
              "name": "volume-0-3",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "size": 10000000000,
              "volume_type": "l_ssd"
            }

+ Response 201 (application/json)
 
    + Headers
                
            https://api.cloud.online.net/volumes/c675f420-cfeb-48ff-ba2a-9d2a4dbe3fcd

    + Body

            {
              "volume": {
                "export_uri": null, 
                "id": "c675f420-cfeb-48ff-ba2a-9d2a4dbe3fcd", 
                "name": "volume-0-3", 
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a", 
                "server": null, 
                "size": 10000000000, 
                "volume_type": "l_ssd"
              }
            }


##### Retrieves all volumes [GET]

List all volumes associate with your account

The response is an object that has a key called `volumes`. This key contain an array of volume objects each of which contain the standard `volume` attributes.

+ Response 200 (application/json)
    
        {
          "volumes": [
            {
              "export_uri": null,
              "id": "f929fe39-63f8-4be8-a80e-1e9c8ae22a76",
              "name": "volume-0-1",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "server": null,
              "size": 10000000000,
              "volume_type": "l_ssd"
            },
            {
              "export_uri": null,
              "id": "0facb6b5-b117-441a-81c1-f28b1d723779",
              "name": "volume-0-2",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "server": null,
              "size": 20000000000,
              "volume_type": "l_ssd"
            }
          ]
        }


#### Volume [/volumes/{volume_id}]

+ Parameters
    + volume_id (required, string, `f929fe39-63f8-4be8-a80e-1e9c8ae22a76`)... Volume unique identifier

##### Retrieves informations about a volume [GET]

List an individual volume

The response is an object that has a key called `volume`. This key contain a standard `volume` object.

+ Response 200 (application/json)
    
        {
          "volume": {
            "export_uri": null,
            "id": "f929fe39-63f8-4be8-a80e-1e9c8ae22a76",
            "name": "volume-0-1",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "server": null,
            "size": 10000000000,
            "volume_type": "l_ssd"
          }
        }


##### Delete a volume [DELETE]

Delete a volume

The response code is a 204, which means that the action was successful with no returned body data.

+ Response 204 (application/json)


### group Snapshots

A snapshot is a full-volume copy stored in our secure data centers.

#### Snapshots [/snapshots]

##### Create a snapshot [POST]

Create a new server

The response is an object that has a key called `snapshot`. This key contain a standard `snapshot` object.

+ Attributes

    + name: `` (string, required) - Human readable snapshot name
    + organization: `000a115d-2852-4b0a-9ce8-47f1134ba95a` (string, required) - Unique organization identifier
    + volume_id: `701a8946-ff9d-4579-95e3-1c2c2d0f892d` (string, required) - Unique volume identifier

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
                "name": "snapshot-0-1",
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                "volume_id": "701a8946-ff9d-4579-95e3-1c2c2d0f892d"
            }

+ Response 200 (application/json)

        {
          "snapshot": {
            "base_volume": {
              "id": "701a8946-ff9d-4579-95e3-1c2c2d0f892d",
              "name": "vol simple snapshot"
            },
            "creation_date": "2014-05-22T12:10:05.596769+00:00",
            "id": "f0361e7b-cbe4-4882-a999-945192b7171b",
            "name": "snapshot-0-1",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "size": 10000000000,
            "state": "snapshotting",
            "volume_type": "l_ssd"
          }
        }


##### List all snapshots [GET]

List all snapshots associate with your account

The response is an object that has a key called `snapshots`. This key contain an array of snapshot objects each of which contain the standard `snapshot` attributes.

+ Response 200 (application/json)

        {
          "snapshots": [
            {
              "base_volume": {
                "id": "09a4184c-733b-43c8-99c3-f1dde30536fe",
                "name": "vol simple snapshot"
              },
              "creation_date": "2014-05-22T12:11:06.055998+00:00",
              "id": "6f418e5f-b42d-4423-a0b5-349c74c454a4",
              "name": "snapshot-0-1",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "size": 10000000000,
              "state": "snapshotting",
              "volume_type": "l_ssd"
            },
            {
              "base_volume": {
                "id": "09a4184c-733b-43c8-99c3-f1dde30536fe",
                "name": "vol simple snapshot"
              },
              "creation_date": "2014-05-22T12:13:09.877961+00:00",
              "id": "c6ff5501-eb35-44b8-aa01-8777211a830b",
              "name": "snapshot-0-2",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "size": 10000000000,
              "state": "snapshotting",
              "volume_type": "l_ssd"
            }
          ]
        }

#### Snapshot [/snapshots/{snapshot_id}]

+ Parameters
    + snapshot_id: `6f418e5f-b42d-4423-a0b5-349c74c454a4` (string, required) - Snapshot unique identifier

##### Retrieve a snapshot [GET]

List an individual snapshot

The response is an object that has a key called `snapshot`. This key contain a standard `snapshot` object.

+ Response 200 (application/json)

        {
          "snapshot": {
            "base_volume": {
              "id": "09a4184c-733b-43c8-99c3-f1dde30536fe",
              "name": "vol simple snapshot"
            },
            "creation_date": "2014-05-22T12:11:06.055998+00:00",
            "id": "6f418e5f-b42d-4423-a0b5-349c74c454a4",
            "name": "snapshot-0-1",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "size": 10000000000,
            "state": "snapshotting",
            "volume_type": "l_ssd"
          }
        }

##### Update a snapshot [PUT]

Update details about a snapshot

The response is an object that has a key called `snapshot`. This key contain a standard `snapshot` object.

+ Attributes
    + organization: `000a115d-2852-4b0a-9ce8-47f1134ba95a` (string, required) - Organization unique identifier

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
                "organization": "f1350c5d-f1d8-4f9d-b114-6053905578e1"
            }


+ Response 200 (application/json)

        {
          "snapshot": {
            "base_volume": {
              "id": "09a4184c-733b-43c8-99c3-f1dde30536fe",
              "name": "vol simple snapshot"
            },
            "creation_date": "2014-05-22T12:11:06.055998+00:00",
            "id": "6f418e5f-b42d-4423-a0b5-349c74c454a4",
            "name": "snapshot-0-1",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "size": 10000000000,
            "state": "snapshotting",
            "volume_type": "l_ssd"
          }
        }

##### Remove a snapshot [DELETE]

Delete a snapshot

The response code is a 204, which means that the action was successful with no returned body data.

+ Response 204

### group Images

Images allow you to create series of servers with predefined configuration.
For instance, you can prepare to scale your serving capacity with a frontend image for an Apache server.

#### Images [/images]

##### Create a new image [POST]

Create a new image

The response is an object that has a key called `image`. This key contain a standard `image` object.

+ Attributes

    + organization: `000a115d-2852-4b0a-9ce8-47f1134ba95a` (string, required) - Organization unique identifier
    + name: `my_image` (string, required) - The image name
    + arch: `arm` (string, required) - The architecture type
    + root_volume: `f0361e7b-cbe4-4882-a999-945192b7171b` (string, required) - The root volume unique identifier

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                "arch": "arm",
                "name": "my_image",
                "root_volume": "f0361e7b-cbe4-4882-a999-945192b7171b"
            }

+ Response 201 (application/json)

        {
          "image": {
            "arch": "arm",
            "creation_date": "2014-05-22T12:56:56.984011+00:00",
            "extra_volumes": "[]",
            "from_image": null,
            "from_server": null,
            "id": "98bf3ac2-a1f5-471d-8c8f-1b706ab57ef0",
            "marketplace_key": null,
            "modification_date": "2014-05-22T12:56:56.984011+00:00",
            "name": "my_image",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "public": false,
            "root_volume": {
              "id": "f0361e7b-cbe4-4882-a999-945192b7171b",
              "name": "vol-0-1"
            }
          }
        }

##### List all images [GET]

List all images associate with your account

The response is an object that has a key called `images`. This key contain an array of image objects each of which contain the standard `images` attributes.

+ Response 200 (application/json)

        {
          "images": [
            {
              "arch": "arm",
              "creation_date": "2014-05-22T12:56:56.984011+00:00",
              "extra_volumes": "[]",
              "from_image": null,
              "from_server": null,
              "id": "98bf3ac2-a1f5-471d-8c8f-1b706ab57ef0",
              "marketplace_key": null,
              "modification_date": "2014-05-22T12:56:56.984011+00:00",
              "name": "my_image",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "public": false,
              "root_volume": {
                "id": "f0361e7b-cbe4-4882-a999-945192b7171b",
                "name": "vol-0-1"
              }
            },
            {
              "arch": "arm",
              "creation_date": "2014-05-22T12:57:22.514299+00:00",
              "extra_volumes": "[]",
              "from_image": null,
              "from_server": null,
              "id": "1f73d975-35fc-4365-9ead-8dab7e54152f",
              "marketplace_key": null,
              "modification_date": "2014-05-22T12:57:22.514299+00:00",
              "name": "my_image_1",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "public": false,
              "root_volume": {
                "id": "f0361e7b-cbe4-4882-a999-945192b7171b",
                "name": "vol-0-2"
              }
            }
          ]
        }

#### Operation on a single image [/images/{image_id}]

+ Parameters
    + image_id (required, string, `98bf3ac2-a1f5-471d-8c8f-1b706ab57ef0`)... Image unique identifier

##### Retrieves an image [GET]

List an individual image

The response is an object that has a key called `image`. This key contain a standard `image` object.

+ Response 200 (application/json)

        {
          "image": {
            "arch": "arm",
            "creation_date": "2014-05-22T12:56:56.984011+00:00",
            "extra_volumes": "[]",
            "from_image": null,
            "from_server": null,
            "id": "98bf3ac2-a1f5-471d-8c8f-1b706ab57ef0",
            "marketplace_key": null,
            "modification_date": "2014-05-22T12:56:56.984011+00:00",
            "name": "my_image",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "public": false,
            "root_volume": {
              "id": "f0361e7b-cbe4-4882-a999-945192b7171b",
              "name": "vol-0-1"
            }
          }
        }

##### Update an image [PUT]

Update details about a image

The response is an object that has a key called `image`. This key contain a standard `image` object.

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
                "arch": "arm", 
                "creation_date": "2014-05-22T12:57:22.514299+00:00", 
                "extra_volumes": "[]", 
                "from_image": null, 
                "from_server": null, 
                "id": "1f73d975-35fc-4365-9ead-8dab7e54152f", 
                "marketplace_key": null, 
                "modification_date": "2014-05-22T12:58:42.511040+00:00", 
                "name": "my_image_old", 
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a", 
                "public": false, 
                "root_volume": {
                  "id": "f0361e7b-cbe4-4882-a999-945192b7171b", 
                  "name": "vol-0-1"
                }
            }


+ Response 200 (application/json)

        {
          "image": {
            "arch": "arm",
            "creation_date": "2014-05-22T12:56:56.984011+00:00",
            "extra_volumes": "[]",
            "from_image": null,
            "from_server": null,
            "id": "98bf3ac2-a1f5-471d-8c8f-1b706ab57ef0",
            "marketplace_key": null,
            "modification_date": "2014-05-22T13:00:15.462764+00:00",
            "name": "my_image_old",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "public": false,
            "root_volume": {
              "id": "f0361e7b-cbe4-4882-a999-945192b7171b",
              "name": "TOTO"
            }
          }
        }


##### Delete an image [DELETE]

Delete an image

The response code is a 204, which means that the action was successful with no returned body data.

+ Response 204 (application/json)

### group IPs

A reserved IP address is a static IP address designed for cloud computing.
Reserved IPs address allow you to mask the failure of a server rapidly reallocating the IPs address to another server in your account.

#### IPs [/ips]

##### Create a new IP [POST]

Create a new reserved IP address

The response is an object that has a key called `ip`. This key contain a standard `ip` object.

+ Attributes

    + organization: `000a115d-2852-4b0a-9ce8-47f1134ba95a` (string, required) - Organization unique identifier

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a"
            }

+ Response 201 (application/json)

            {
              "ip": {
                "address": "212.47.226.88",
                "id": "b50cd740-892d-47d3-8cbf-88510ef626e7",
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                "server": null
              }
            }

##### Retrieves all IPs addresses [GET]

List all IPs associate with your account

The response is an object that has a key called `ips`. This key contain an array of ip objects each of which contain the standard `ip` attributes.

+ Response 200 (application/json)

        {
          "ips": [
            {
              "address": "212.47.226.88",
              "id": "b50cd740-892d-47d3-8cbf-88510ef626e7",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "server": null
            }
          ]
        }

#### IP [/ips/{ip_id}]

+ Parameters
    + ip_id (required, string, `b50cd740-892d-47d3-8cbf-88510ef626e7`)... Ip unique identifier

##### Retrieve an IP address [GET]

List an individual IP address

The response is an object that has a key called `ip`. This key contain a standard `ip` object.

+ Response 200 (application/json)

        {
          "ip": {
            "address": "212.47.226.88",
            "id": "b50cd740-892d-47d3-8cbf-88510ef626e7",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "server": null
          }
        }

##### Attach an IP address [PUT]

Allow you to remap an IP address to another server

The response is an object that has a key called `ip`. This key contain a standard `ip` object.

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
                "address": "212.47.226.88",
                "id": "b50cd740-892d-47d3-8cbf-88510ef626e7",
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                "server": "c2d8994f-1582-413e-8d48-c53076db06cc"
            }


+ Response 200 (application/json)

        {
          "ip": {
            "address": "212.47.226.88",
            "id": "b50cd740-892d-47d3-8cbf-88510ef626e7",
            "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
            "server": {
              "id": "c2d8994f-1582-413e-8d48-c53076db06cc",
              "name": "default_server_name - acfb51"
            }
          }
        }


##### Remove an IP address [DELETE]

Delete a server

The response code is a 204, which means that the action was successful with no returned body data.

+ Response 204 (application/json)


### group Security groups

Security groups are like a virtual firewall. With security groups, you can define rules that restrict network access to your servers.

#### Security Groups [/security_groups]

##### Create a security group [POST]

Create a new security group

The response is an object that has a key called `security_group`. This key contain a standard `security_group` object.

+ Attributes

    + organization: `000a115d-2852-4b0a-9ce8-47f1134ba95a` (string, required) - Organization unique identifier
    + name: `security-group-01` (string, required) - The security group name
    + description: `arm` (string, required) -  The security group description

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                "name": "security-group-01",
                "description": "Security group 01"
            }

+ Response 201 (application/json)

        {
          "security_group": {
              "description": "Security group 01",
              "enable_default_security": true,
              "id": "adb5887b-5ab5-445a-ae70-276df95a9852",
              "name": "security-group-01",
              "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
              "organization_default": false,
              "servers": []
          }
        }

##### List all security groups [GET]

List all security groups associate with your account

The response is an object that has a key called `security_groups`. This key contain an array of security group objects each of which contain the standard `security_groups` attributes.

+ Response 200 (application/json)

        {
            "security_groups": [
                {
                    "description": "Base security group",
                    "enable_default_security": true,
                    "id": "000a115d-2852-4b1a-9ce8-47f1134ba95a",
                    "name": "Base group",
                    "organization": "ecc1c86a-eabb-43a7-9c0a-77e371753c0a",
                    "organization_default": true,
                    "servers": [
                        {
                            "id": "b5614869-1967-9ce8-8cd2-801febf9a3f9",
                            "name": "scw-9b0823"
                        },
                        {
                            "id": "4167bf23-9ce8-4790-2852-d7c5b86934df",
                            "name": "scw-9b088e"
                        }
                    ]
                }
            ]
        }

#### Operation on a security groups [/security_groups/{group_id}]

+ Parameters
    + group_id (required, string, `000a115d-2852-4b1a-9ce8-47f1134ba95a`)... Security group id unique identifier

##### Retrieves a security group [GET]

List an individual security group

The response is an object that has a key called `security_group`. This key contain a standard `security_group` object.

+ Response 200 (application/json)

        {
          "security_group": {
            "description": "Base security group",
            "enable_default_security": true,
            "id": "000a115d-2852-4b1a-9ce8-47f1134ba95a",
            "name": "Base group",
            "organization": "ecc1c86a-eabb-43a7-9c0a-77e371753c0a",
            "organization_default": true,
            "servers": [
                {
                    "id": "b5614869-1967-9ce8-8cd2-801febf9a3f9",
                    "name": "scw-9b0823"
                },
                {
                    "id": "4167bf23-9ce8-4790-2852-d7c5b86934df",
                    "name": "scw-9b088e"
                }
            ]
          }
        }

##### Update a security group [PUT]

Update a security group details

The response is an object that has a key called `security_group`. This key contain a standard `security_group` object.

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
                "organization": "000a115d-2852-4b0a-9ce8-47f1134ba95a",
                "name": "security-group-02",
                "description": "Security group 02"
            }


+ Response 200 (application/json)

        {
          "security_group": {
            "description": "Security group 02",
            "enable_default_security": true,
            "id": "000a115d-2852-4b1a-9ce8-47f1134ba95a",
            "name": "security-group-02",
            "organization": "ecc1c86a-eabb-43a7-9c0a-77e371753c0a",
            "organization_default": true,
            "servers": [
                {
                    "id": "b5614869-1967-9ce8-8cd2-801febf9a3f9",
                    "name": "scw-9b0823"
                },
                {
                    "id": "4167bf23-9ce8-4790-2852-d7c5b86934df",
                    "name": "scw-9b088e"
                }
            ]
          }
        }


##### Delete a security group [DELETE]

Delete a security group

The response code is a 204, which means that the action was successful with no returned body data.

+ Response 204

#### Manage rules [/security_groups/{group_id}/rules]

+ Parameters
    + group_id: `000a115d-2852-4b1a-9ce8-47f1134ba95a` (string, required) - Security group unique identifier

##### Create a new rule [POST]

Create a new rule

The response is an object that has a key called `rule`. This key contain a standard `rule` object.

action: "accept"
direction: "outbound"
ip_range: "0.0.0.0/0"
protocol: "ICMP"

+ Attributes

    + organization: `required, string, `000a115d-2852-4b0a-9ce8-47f1134ba95a` (string, required) - Organization unique identifier
    + action: `drop` (string, required) - The rule action (accept, drop)
    + direction: `'inbound` (string, required) - The rule direction (inbound, outbound)
    + ip_range: `0.0.0.0/0` (string, required) - The IPs range, must be an IPv4 range
    + protocol: `TCP` (string, required) - The rule protocol (TCP, UDP, ICMP)
    + dest_port_from: `25` (string, optional) The port between 1 and 65535

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
              "action": "drop",
              "direction": "inbound",
              "ip_range": "0.0.0.0/0",
              "protocol": "TCP"
            }

+ Response 201 (application/json)

        {
          "rule": {
              "direction": "inbound",
              "protocol": "TCP",
              "ip_range": "0.0.0.0/0",
              "dest_port_from": null,
              "action": "drop",
              "position": 2,
              "dest_port_to": null,
              "editable": null,
              "id": "ef2136c9-6c21-491a-b238-b38de24726a7"
          }
        }

##### List all rules [GET]

List all rules for a security group

The response is an object that has a key called `rules`. This key contain an array of rules for a security group each of which contain the standard `rule` attributes.

+ Response 200 (application/json)

        {
            "rules": [
              {
                  "direction": "outbound",
                  "protocol": "TCP",
                  "ip_range": "0.0.0.0/0",
                  "dest_port_from": 25,
                  "action": "drop",
                  "position": 1,
                  "dest_port_to": null,
                  "editable": false,
                  "id": "58909be7-d17c-4ac8-9eb3-23d5fc58abc5"
              }, {
                  "direction": "outbound",
                  "protocol": "TCP",
                  "ip_range": "0.0.0.0/0",
                  "dest_port_from": 465,
                  "action": "drop",
                  "position": 2,
                  "dest_port_to": null,
                  "editable": false,
                  "id": "25680235-108b-4bbc-8e25-114303d950bd"
              }, {
                  "direction": "outbound",
                  "protocol": "TCP",
                  "ip_range": "0.0.0.0/0",
                  "dest_port_from": 587,
                  "action": "drop",
                  "position": 3,
                  "dest_port_to": null,
                  "editable": false,
                  "id": "4a31b633-118e-4900-bd52-facf1085fc8d"
              }
            ]
        }

#### Operation on a security rule [/security_groups/{group_id}/rules/{rule_id}]

+ Parameters
    + group_id: `000a115d-2852-4b1a-9ce8-47f1134ba95a` (string, required) - Security group unique identifier
    + rule_id: `4a31b633-118e-4900-bd52-facf1085fc8d` (string, required) - Security rule unique identifier

##### Update a security rule [PUT]

Update a security rule

The response is an object that has a key called `rule`. This key contain a standard `rule` object.

+ Request (application/json)

    + Headers
    
            X-Auth-Token: aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee

    + Body

            {
              "action": "drop",
              "direction": "outbound",
              "ip_range": "0.0.0.0/0",
              "protocol": "TCP"
            }


+ Response 200 (application/json)

        {
          "rule": {
              "direction": "outbound",
              "protocol": "TCP",
              "ip_range": "0.0.0.0/0",
              "dest_port_from": null,
              "action": "drop",
              "position": 2,
              "dest_port_to": null,
              "editable": null,
              "id": "ef2136c9-6c21-491a-b238-b38de24726a7"
          }
        }

##### Retrieves a security rule [GET]

List an individual security rule

The response is an object that has a key called `rule`. This key contain a standard `rule` object.

+ Response 200 (application/json)

        {
          "rule": {
              "direction": "outbound",
              "protocol": "TCP",
              "ip_range": "0.0.0.0/0",
              "dest_port_from": null,
              "action": "drop",
              "position": 2,
              "dest_port_to": null,
              "editable": null,
              "id": "ef2136c9-6c21-491a-b238-b38de24726a7"
          }
        }

##### Delete a security rule [DELETE]

Delete and deactivate a security rule

The response code is a 204, which means that the action was successful with no returned body data.

+ Response 204 (application/json)

### group Metadata

Resources related to server Metadata available from your C1 servers at `http://169.254.42.42`

#### C1 server metadata [/conf{?format}]

+ Parameters
    + format (optional, string, `json`)... Rendering format

##### Serves pimouss metadata [GET]
Serves instance metadata using its own IP address as authentication token.

+ Response 200 (application/json)

        {
            "id": "9fc9a037-5eaa-4073-9919-63adbe400ab9",
            "name": "Server 2",
            "organization": "11111111-1111-4111-8111-111111111111",
            "private_ip": "10.42.1.2",
            "public_ip": "42.1.2.3",
            "ssh_public_keys": [
                "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjHvTHk5QY+JZdCvAep6APwOhZvIimlC4aybrXkGSBxpNeZI1f+AexDuFFWGZPb1y135pgTAc7VXpKD2FU2xd4EwsSTHaBcaBIs1HkhpFScTwN15IfLiefIHgjgveP/8U8AKQvCK7oecz3egjvqNtBDDj9cHySpQ6w5Zq/rtF7Ku8xAfBa78NEQrwaYvdfHqI/1APeoo61MJse+xZH2LVHX1EZp79jRbHny/0WkZifVXudDCmM9aqI3G1ZgWTWvFxHW/HTkSLz1v8OHD1ZPOEjIIKLxCoYE4kukK2eVZVUWFb+iU+u6GunwqWUa6W/g+0NzpEoSHVcasIC88d3tBZD",
                "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAutWtCIFyrtcpxBevMyDrNlYabV6cCVPjfWwfuKABofuWwCSX8gP2gSnmjQCdtTwYnz/vAuAXbKxn8pxtUy4c24oRvtwqHpEsFDMpzzMzWtghQFOHEd7NWzda3yDGCaJ8OFD1IkiFad5QNKmOt8nlERBUK9cwbPjzhTnP/o2Odn5nJJ8WySn0/TWwMaHH6hpZTtKMSrIn06Fo5MviPfeZ9Loe8IfgV7llB7ITMFTUKP5vPVvMlPJi8MYeo0AYmhFhbTO5wWj8hK8AJELF9RwMCehcsxjDRxKKbxiv9RL3yIdBH0dftlaNX5rYazRp4zB2BYvfPNjhpTqrY2RdPYAvTw=="
            ],
            "tags": [],
            "volumes": []
        }

+ Response 200 (plain/text)

        NAME='Server 2'
        TAGS=0
        PUBLIC_IP=42.1.2.3
        SSH_PUBLIC_KEYS=2
        SSH_PUBLIC_KEYS_0='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjHvTHk5QY+JZdCvAep6APwOhZvIimlC4aybrXkGSBxpNeZI1f+AexDuFFWGZPb1y135pgTAc7VXpKD2FU2xd4EwsSTHaBcaBIs1HkhpFScTwN15IfLiefIHgjgveP/8U8AKQvCK7oecz3egjvqNtBDDj9cHySpQ6w5Zq/rtF7Ku8xAfBa78NEQrwaYvdfHqI/1APeoo61MJse+xZH2LVHX1EZp79jRbHny/0WkZifVXudDCmM9aqI3G1ZgWTWvFxHW/HTkSLz1v8OHD1ZPOEjIIKLxCoYE4kukK2eVZVUWFb+iU+u6GunwqWUa6W/g+0NzpEoSHVcasIC88d3tBZD'
        SSH_PUBLIC_KEYS_1='ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAutWtCIFyrtcpxBevMyDrNlYabV6cCVPjfWwfuKABofuWwCSX8gP2gSnmjQCdtTwYnz/vAuAXbKxn8pxtUy4c24oRvtwqHpEsFDMpzzMzWtghQFOHEd7NWzda3yDGCaJ8OFD1IkiFad5QNKmOt8nlERBUK9cwbPjzhTnP/o2Odn5nJJ8WySn0/TWwMaHH6hpZTtKMSrIn06Fo5MviPfeZ9Loe8IfgV7llB7ITMFTUKP5vPVvMlPJi8MYeo0AYmhFhbTO5wWj8hK8AJELF9RwMCehcsxjDRxKKbxiv9RL3yIdBH0dftlaNX5rYazRp4zB2BYvfPNjhpTqrY2RdPYAvTw=='
        PRIVATE_IP=10.42.1.2
        VOLUMES=0
        ORGANIZATION=11111111-1111-4111-8111-111111111111
        ID=9fc9a037-5eaa-4073-9919-63adbe400ab9
